### ISSUE TITLE
lin file cannot exists..

### ISSUE THREAD

**Issue by LEE-SEON-WOO** [Hamze-Issa/Spectrometer-GenSpect#1]
load('genhit2000_02.lin', '-mat');
load('genhit2000_01.lin', '-mat');
load('genhit2000_07.lin', '-mat');
load('genhit2000_05.lin', '-mat');

**Comment by Hamze-Issa** [comment]
Hi, 
These are the Hitran database data files. You have to download them yourself as I am not authorized to distribute them. You can find them in https://hitran.org/
Add them to the file path and it should work.

**Comment by OmarBM13** [comment]
Dear Hamze-Issa,

I can't get the files genhit2000_02.lin, genhit2000_01.lin, genhit2000_07.lin, genhit2000_05.lin. Can you provide me with the link of the files? please.

I can't find those files in Hitran's link.

Greetings.

**Comment by Hamze-Issa** [comment]
Hi,
This is the hitran library which not owned by me so I can't send it to you
directly without permission. You can search for it and purchase it from its
owners. I hope that helps. Best of luck with your work.

Hamzeh
